---
printWidth: 100
tabWidth: 4
useTabs: true
trailingComma: all
semi: true
singleQuote: false

overrides:
    - files: "*.md"
      options:
          useTabs: false
          tabWidth: 2
    - files: "*.svelte"
      options:
          parser: svelte

plugins:
    - prettier-plugin-svelte
    - prettier-plugin-organize-imports
